services:
  - type: web
    name: reddit-referral-poster-pro-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_REDIRECT_URI
        value: https://YOUR-RENDER-APP.onrender.com/oauth/callback
      - key: USER_AGENT
        value: referral-poster-pro v2 by u/YOURNAME
